### ISSUE TITLE
Incompatibility with apollo-server ^2.2.0

### ISSUE THREAD

**Issue by jgoux** [prisma/graphql-middleware#75] opened 2018-11-14 13:27 UTC
Hello,

It seems that there is an incompatibility issue between graphql-middleware and apollo-server@^2.2.0

Here you can find an explanation about what is breaking : https://github.com/apollographql/apollo-server/issues/1935#issuecomment-438210375

So apparently something in graphql-middleware is turning the introspection query execution (from `graphql/execution` into a Promise instead of returning an object.

Another related issue : https://github.com/apollographql/apollo-server/issues/1934

In the meantime, the last working version is apollo-server@2.0.5

**Comment by nicklaros** [comment] 2018-11-17 06:35
yap, had this issue as well after update my `apollo-server` dependencies

**Comment by abernix** [comment] 2018-11-21 12:37
I'm curious if anyone experiencing this problem (and has a reproduction) would be willing to try modifying `graphql-middleware`'s [`applicator.ts`](https://github.com/prisma/graphql-middleware/blob/784199ef54cc1f4002d4a0ab3769f9ee77a2fffc/src/applicator.ts) to have it obey [`graphql/introspection`'s `isIntrospectionType`](https://github.com/graphql/graphql-js/blob/74d1e941af54a8c8d0faef063ee7460aebdd8084/src/type/introspection.js#L484) predicate function prior to applying middleware to it.

Essentially, this incompatibility is occurring because the expectation Apollo Server (now) makes about introspection queries is that they should resolve synchronously (as in, they should not have asynchronous properties or resolvers).  This is an expectation seems to be corroborated by `graphql` itself by logic similar/related to that in https://github.com/graphql/graphql-js/pull/1120.

My claim is that that predicate should be applied prior to wrapping a resolver to maintain the synchronous execution dynamics of introspection queries.

**Comment by israelglar** [comment] 2018-11-23 15:20
Hello! @abernix  I'm having the same issue but can't figure out what to do to applicator.ts to fix it but I will continue to try :+1: 
@maticzav since this issue is assigned to you, do have an idea when this will be resolved? Thanks!

**Comment by resao** [comment] 2018-12-03 08:53
The same issue is unfortunately present when used with apollo-server-azure-functions. Although in my case I can't find an appropriate version of apollo-server-azure-functions to roll back to :(

**Comment by ellipticaldoor** [comment] 2018-12-06 14:19
I have also this problem whit graphql-shield

**Comment by resao** [comment] 2018-12-11 08:59
@ellipticaldoor 

There is a temporary (but not very nice) solution which appears to allow "apollo-server-azure-functions": "2.2.6", "graphql-middleware": "^2.0.2" and "graphql-shield": "^4.1.0" work alongside each other.

Following this issue comment https://github.com/apollographql/apollo-server/issues/1935#issuecomment-436962565 I was able to patch the apollo-server-core dependency in my solution and it now works

**Comment by ellipticaldoor** [comment] 2018-12-13 20:43
I think I will wait for a better fix :/

**Closed** 2018-12-18 10:59 UTC
Labels: bug

**Comment by chanlito** [comment] 2018-12-19 04:01
@ellipticaldoor I'm using graphql-shield v5 seems to be working now.

**Comment by kallaspriit** [comment] 2018-12-19 09:00
I can also confirm that with the latest version it works nicely again :)
